### ISSUE TITLE
Pls no rotation

### ISSUE THREAD

**Issue by DeadlyArtist** [dwonderley/mookAI#11]
Just saw it rotated my token. Since I don't use top down tokens this behaviour is incredibly ugly. :)

**Comment by dwonderley** [comment]
There's already an open issue for this, so I'm going to close it.

Rotation needs to be enabled so that mookAI can use the token's vision cone. If you don't want the tokens to rotate, you can set the "Lock Rotation" field on the token's configuration.

It's probably a pain to do that for all tokens, so I'm probably going to add an option to lock tokens before mookAI moves them in the near future
